title: wiki.central.ntua.gr
description: Σελίδες wiki του Κέντρου Ηλεκτρονικών Υπολογιστών του ΕΜΠ
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Κέντρο Ηλεκτρονικών Υπολογιστών
repo_url: "https://github.com/christodoulos/wiki.central.ntua.gr"
edit_on_github: false
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
